"""GroundLoop M5 bounded evidence-group contracts and reference semantics."""

from groundloop.m5.domain import (
    ClaimCertificateArtifact,
    ClaimSupportKind,
    CombinedAnswerState,
    CombinedClaimState,
    ConstructionKind,
    EvidenceGroupFamily,
    EvidenceGroupFamilyRetirement,
    EvidenceGroupType,
    EvidenceGroupValidity,
    EvidenceGroupVersion,
    EvidenceRequirementVersion,
    GroupCertificateRow,
    GroupMatchingCertificateArtifact,
    GroupState,
    ObservationCurrencyInterval,
    RequirementObservationRecord,
    RequirementState,
    RequirementWitness,
    SnapshotPoint,
)
from groundloop.m5.events import (
    FailureInjector,
    M5ApplyResult,
    ObserveRequirementEvent,
    RegisterGroupEvent,
    ReplaceGroupEvent,
    RetireGroupEvent,
    apply_m5_event,
)
from groundloop.m5.incremental_overlay import (
    CommittedOverlayEvent,
    M5IncrementalOverlay,
    M5OverlayApplyResult,
    M5OverlayWork,
    OverlayFailureInjector,
    PreparedM5OverlayPatch,
)
from groundloop.m5.reference import (
    CANONICAL_REQUIREMENT_TASK,
    M5ReferenceStates,
    build_reference_claim_certificate,
    build_reference_group_certificate,
    compute_reference_states,
    derive_active_requirement_witnesses,
    maximum_matching_with_unmatched_branch,
    validate_claim_certificate,
    validate_group_certificate,
)
from groundloop.m5.repository import M5Repository, M5RepositorySnapshot

__all__ = [
    "CANONICAL_REQUIREMENT_TASK",
    "ClaimCertificateArtifact",
    "ClaimSupportKind",
    "CombinedAnswerState",
    "CombinedClaimState",
    "ConstructionKind",
    "CommittedOverlayEvent",
    "EvidenceGroupFamily",
    "EvidenceGroupFamilyRetirement",
    "EvidenceGroupType",
    "EvidenceGroupValidity",
    "EvidenceGroupVersion",
    "EvidenceRequirementVersion",
    "FailureInjector",
    "GroupCertificateRow",
    "GroupMatchingCertificateArtifact",
    "GroupState",
    "M5ApplyResult",
    "M5IncrementalOverlay",
    "M5OverlayApplyResult",
    "M5OverlayWork",
    "M5ReferenceStates",
    "M5Repository",
    "M5RepositorySnapshot",
    "ObservationCurrencyInterval",
    "OverlayFailureInjector",
    "ObserveRequirementEvent",
    "RegisterGroupEvent",
    "ReplaceGroupEvent",
    "RequirementObservationRecord",
    "RequirementState",
    "RequirementWitness",
    "RetireGroupEvent",
    "SnapshotPoint",
    "PreparedM5OverlayPatch",
    "apply_m5_event",
    "build_reference_claim_certificate",
    "build_reference_group_certificate",
    "compute_reference_states",
    "derive_active_requirement_witnesses",
    "maximum_matching_with_unmatched_branch",
    "validate_claim_certificate",
    "validate_group_certificate",
]
